function [] = CreateEnvironment()
axis equal;
view(3);
camlight;
hold on;

            % Create the Floor
            surf([-5,-5;5,5] ...
            ,[-5,4;-5,4] ...
            ,[0.01,0.01;0.01,0.01] ...
            ,'CData',imread('concrete.jpg') ...
            ,'FaceColor','texturemap');

            %Create the walls
            surf([-5,5;-5,5] ...
            ,[4,4;4,4] ...
            ,[0,0;4,4] ...
            ,'CData',imread('concrete.jpg') ...
            ,'FaceColor','texturemap');

            surf([-5,5;-5,5] ...
            ,[-5,-5;-5,-5] ...
            ,[0,0;4,4] ...
            ,'CData',imread('concrete.jpg') ...
            ,'FaceColor','texturemap');

            surf([5,5;5,5] ...
            ,[-5,4;-5,4] ...
            ,[0,0;4,4] ...
            ,'CData',imread('concrete.jpg') ...
            ,'FaceColor','texturemap');

            surf([-5,-5;-5,-5] ...
            ,[-5,4;-5,4] ...
            ,[0,0;4,4] ...
            ,'CData',imread('concrete.jpg') ...
            ,'FaceColor','texturemap');

            %Create Background
            surf([-5,5;-5,5] ...
            ,[8,8;8,8] ...
            ,[0,0;4,4] ...
            ,'CData',imread('space.jpg') ...
            ,'FaceColor','texturemap');

            surf([-5,-5;-5,-5] ...
            ,[4,8;4,8] ...
            ,[0,0;4,4] ...
            ,'CData',imread('space.jpg') ...
            ,'FaceColor','texturemap');

            surf([5,5;5,5] ...
            ,[4,8;4,8] ...
            ,[0,0;4,4] ...
            ,'CData',imread('space.jpg') ...
            ,'FaceColor','texturemap');

            surf([-5,-5;5,5] ...
            ,[4,8;4,8] ...
            ,[0.01,0.01;0.01,0.01] ...
            ,'CData',imread('space.jpg') ...
            ,'FaceColor','texturemap');

            axis ([-5 5 -5 8 0 4])
%% Load Door into Matlab
door = PlaceObject('door.ply', [0,4,0]);
fireExt = PlaceObject('fireExtinguisher.ply', [4.9,1.5,1.5]);

% door2 = PlaceObject('door2.ply', [0,4,0]);
curtain = PlaceObject('lightCurtain1.ply', [4.85,-2,0]);
curtain2 = PlaceObject('lightCurtain2.ply', [-4.85,-2,0]);

%% Load EStop
EStop = PlaceObject('emergencyStopButton.ply', [4,4,2]);
%% Load Tools
camera = PlaceObject('camera.ply',[1.2,3.2,0]);
screwdriver = PlaceObject('screwdriver.ply', [1.2,3.3,0]);
toolbox = PlaceObject('toolbox.ply', [1.2,3.5,0]);
broom = PlaceObject('broom.ply', [1.2,3,0]);


%% Load Fences
PlaceObject('barrier1.5x0.2x1m.ply', [0.75,0.8,0]);
PlaceObject('barrier1.5x0.2x1m.ply', [-0.75,0.8,0]);
% PlaceObject('barrier1.5x0.2x1m.ply', [0.75,-1.5,0]);
% PlaceObject('barrier1.5x0.2x1m.ply', [-0.75,-1.5,0]);
sideBarrier1 = PlaceObject('barrier1.5x0.2x1m.ply', [-3,1.5,0]);
sideBarrier2 = PlaceObject('barrier1.5x0.2x1m.ply', [-1.5,-1.5,0]);
sideBarrier3 = PlaceObject('barrier1.5x0.2x1m.ply', [-1.5,1.5,0]);
sideBarrier4 = PlaceObject('barrier1.5x0.2x1m.ply', [-3,-1.5,0]);

sideBarrier1_Vert = [get(sideBarrier1, 'Vertices'), ones(size(get(sideBarrier1,'Vertices'),1),1)] *trotz(pi/2);
set(sideBarrier1, 'Vertices', sideBarrier1_Vert(:,1:3));	

sideBarrier2_Vert = [get(sideBarrier2, 'Vertices'), ones(size(get(sideBarrier2,'Vertices'),1),1)] *trotz(pi/2);
set(sideBarrier2, 'Vertices', sideBarrier2_Vert(:,1:3));

sideBarrier3_Vert = [get(sideBarrier3, 'Vertices'), ones(size(get(sideBarrier3,'Vertices'),1),1)] *trotz(pi/2);
set(sideBarrier3, 'Vertices', sideBarrier3_Vert(:,1:3));	

sideBarrier4_Vert = [get(sideBarrier4, 'Vertices'), ones(size(get(sideBarrier4,'Vertices'),1),1)] *trotz(pi/2);
set(sideBarrier4, 'Vertices', sideBarrier4_Vert(:,1:3));

%Load safety zone
            surf([-1.6,-1.6;1.6,1.6] ...
            ,[0.75,4;0.75,4] ...
            ,[0.02,0.02;0.02,0.02] ...
            ,'CData',imread('tape2.jpg') ...
            ,'FaceColor','texturemap');
